<?php /** @var \OleksiiBezpoiasnyi\RegularCustomer\Block\PersonalDiscountInfo $block */
/** @var \Magento\Framework\Escaper $escaper */
if ($personalDiscounts = $block->getPersonalDiscount()):
/** @var \OleksiiBezpoiasnyi\RegularCustomer\Api\Data\DiscountRequestInterface $personalDiscount */
    foreach ($personalDiscounts as $personalDiscount) :?>
    <p>
        <span><?= $escaper->escapeHtml(__('Product: ')) ?></span>
        <span><?= $escaper->escapeHtml($personalDiscount->getProductId()) ?></span>
    </p>
    <p>
        <span><?= $escaper->escapeHtml(__('Request status:')) ?></span>
        <span><?= $escaper->escapeHtml($block->getStatusMessage($personalDiscount)) ?></span>
    </p>
    <?php endforeach; ?>
<?php else: ?>
    <p><?= $escaper->escapeHtml(__('No request to register in loyalty program')) ?></p>
<?php endif; ?>
