version: '3.7'
services:
  php:
    container_name: oleksii-bezpoiasnyi-dev.local-prod
    image: 'defaultvalue/php:7.4-production'
    user: 'docker:docker'
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    restart: always
    labels:
      - traefik.enable=true
      - 'traefik.http.routers.oleksii-bezpoiasnyi-dev-local-http.rule=Host(`oleksii-bezpoiasnyi-dev.local`,`www.oleksii-bezpoiasnyi-dev.local`,`oleksii-bezpoiasnyi-second-dev.local`,`www.oleksii-bezpoiasnyi-second-dev.local`)'
      - traefik.http.routers.oleksii-bezpoiasnyi-dev-local-http.entrypoints=http
      - traefik.http.routers.oleksii-bezpoiasnyi-dev-local-http.service=oleksii-bezpoiasnyi-dev-local-http
      - traefik.http.services.oleksii-bezpoiasnyi-dev-local-http.loadbalancer.server.port=80
      - traefik.http.services.oleksii-bezpoiasnyi-dev-local-http.loadbalancer.server.scheme=http
      - 'traefik.http.routers.oleksii-bezpoiasnyi-dev-local-https.rule=Host(`oleksii-bezpoiasnyi-dev.local`,`www.oleksii-bezpoiasnyi-dev.local`,`oleksii-bezpoiasnyi-second-dev.local`,`www.oleksii-bezpoiasnyi-second-dev.local`)'
      - traefik.http.routers.oleksii-bezpoiasnyi-dev-local-https.entrypoints=https
      - traefik.http.routers.oleksii-bezpoiasnyi-dev-local-https.tls=true
      - traefik.http.routers.oleksii-bezpoiasnyi-dev-local-https.service=oleksii-bezpoiasnyi-dev-local-https
      - traefik.http.services.oleksii-bezpoiasnyi-dev-local-https.loadbalancer.server.port=443
      - traefik.http.services.oleksii-bezpoiasnyi-dev-local-https.loadbalancer.server.scheme=https
    extra_hosts:
      - 'oleksii-bezpoiasnyi-dev.local www.oleksii-bezpoiasnyi-dev.local oleksii-bezpoiasnyi-second-dev.local www.oleksii-bezpoiasnyi-second-dev.local:127.0.0.1'
    environment:
      - COMPOSER_VERSION=1
    volumes:
      - '../../:/var/www/html'
      - '${SSL_CERTIFICATES_DIR}:/certs'
      - './apache/virtual-host.conf:/etc/apache2/sites-enabled/000-default.conf:ro'
  mysql:
    image: 'mysql:8.0'
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    volumes:
      - 'mysql_prod_data:/var/lib/mysql'
      - './mysql/my.cnf:/etc/my.cnf:ro'
  elasticsearch:
    image: 'elasticsearch:7.7.1'
    environment:
      - network.host=0.0.0.0
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - xpack.security.enabled=false
      - indices.query.bool.max_clause_count=10240
      - 'ES_JAVA_OPTS=-Xms1024m -Xmx1024m'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    restart: always
    volumes:
      - 'elasticsearch_prod_data:/usr/share/elasticsearch/data:rw'
  redis:
    image: 'redis:5.0'
    restart: always
volumes:
  mysql_prod_data:
    external: false
  elasticsearch_prod_data:
    external: false
